name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          dry_run: ci
          email: example@example.com
          api_token: foobar
          subdomain: subdomain
          jira_project: PROJ
          release_name: New Release Name
          tickets: PROJ-1,PROJ-2,PROJ-9
